[2025-05-01 17:59:28,210] 21 root - INFO - Data read successfully from D:\campusx_dsmp2\9. MLOps revisited\cars24_mlops_project\artifacts\data_ingestion\train\train.csv and D:\campusx_dsmp2\9. MLOps revisited\cars24_mlops_project\artifacts\data_ingestion\test\test.csv
[2025-05-01 17:59:30,400] 121 root - ERROR - Error during transformation pipeline
Traceback (most recent call last):
  File "D:\campusx_dsmp2\9. MLOps revisited\cars24_mlops_project\src\components\data_transformation.py", line 106, in perform_transformation
    transformed_train_df = pd.DataFrame(
  File "C:\Users\iampr\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 758, in __init__
    mgr = ndarray_to_mgr(
  File "C:\Users\iampr\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\internals\construction.py", line 337, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "C:\Users\iampr\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\internals\construction.py", line 408, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (800, 881), indices imply (800, 882)
